[Unit]
Description=QEMU-ktest
After=local-fs.target network-online.target network.target
After=rsyslog.service
Wants=local-fs.target network-online.target network.target

[Service]
Type=oneshot
IgnoreSIGPIPE=no
ExecStart=/root/ktest.boot
ExecStopPost=/sbin/poweroff -f
TimeoutSec=0
StandardOutput=tty

[Install]
WantedBy=multi-user.target
