name: basictest

on:
  workflow_dispatch:
 
defaults:
  run:
    shell: bash

jobs:
  build-erofs-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build erofs-utils
        run: |
          sudo apt -qq update
          sudo apt-get install -y libfuse-dev libselinux1-dev libzstd-dev libfuse2 attr xattr
          curl -L https://github.com/lz4/lz4/archive/refs/tags/v1.9.4.tar.gz | tar -zxv
          make BUILD_SHARED=no -C lz4-1.9.4 && lz4libdir=$(pwd)/lz4-1.9.4/lib
          git clone https://github.com/Kyrie112/erofs-utils.git
          cd erofs-utils
          mkdir output
          ./autogen.sh && ./configure --enable-debug --enable-werror --enable-fuse --with-selinux --with-libzstd \
              --disable-multithreading \
              --prefix=$(pwd)/output \
              --with-lz4-incdir=${lz4libdir} --with-lz4-libdir=${lz4libdir}
          sudo make check
          make install
        timeout-minutes: 10
      - name: Upload results if build failed
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: results-output
          path: |
            erofs-utils/tests/results/erofs
      - name: Upload erofs-utils
        uses: actions/upload-artifact@v4
        with:
          name: erofs-utils
          path: |
            erofs-utils/output

  run-stress-test:
    runs-on: ubuntu-latest
    needs: build-erofs-utils
    steps:
      - name: Download erofs-utils prebuilts
        uses: actions/download-artifact@v4
        with:
          name: erofs-utils
      - name: Make erofs file image
        run: |
          sudo apt -qq update
          sudo apt-get install -y libfuse2
          mkdir silesia out
          wget -O silesia.zip https://mattmahoney.net/dc/silesia.zip
          unzip silesia.zip -d silesia
          chmod +x bin/mkfs.erofs bin/erofsfuse
          bin/mkfs.erofs -C4096 silesia.erofs.img silesia 
          bin/erofsfuse silesia.erofs.img out
      - name: Run stress test
        run: |
          sudo apt-get install gcc
          git clone https://github.com/erofs/erofsstress.git
          cd erofsstress
          gcc stress.c -o stress
          ./stress -l100 -p2 ../silesia
